//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAssinment3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostDb
    {
        public int Pid { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string Author { get; set; }
    }
}
